version: '3.8'

services:

  web:
    build: .
    image: web
    container_name: web
    ports:
      - "5000:5000"
    command: python3 -m flask run --host="0.0.0.0:5000"
    environment:
#      - FLASK_DEBUG=1
#      - APP_SETTINGS=project.server.config.DevelopmentConfig
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

  worker:
    build: .
    command: celery --app evaluate_api.service.evaluator.seller_app worker -l INFO --pool=solo
#    volumes:
#      - .:/usr/src/app
    environment:
#      - FLASK_DEBUG=1
#      - APP_SETTINGS=project.server.config.DevelopmentConfig
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis

  redis:
    image: redis:alpine