version: '3.8'

services:

  web:
    build: .
    container_name: web
    working_dir: .
    ports:
      - "5000:5000"
    environment:
      - MONGO_HOST=mongodb://mongodb0.example.com:27017
      - FLASK_APP=proj_stat.app
      - FLASK_ENV=development
    entrypoint: "python"
    command: " -m flask run --host=0.0.0.0"
    depends_on:
      - database

  database:
    image: mongo
    container_name: database
    working_dir: /data/db
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
