version: '3.8'

services:

  web:
    build: .
    container_name: web
    working_dir: /flask_server
    ports:
      - "5000:5000"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - REDIS_HOST=redis
    depends_on:
      - redis

  worker:
    build: .
    container_name: worker
    working_dir: /flask_server
    entrypoint: "python"
    command: " -m celery --app evaluate_api.service.evaluator.celler_app worker -l INFO --concurrency=4"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis

  redis:
    image: redis:alpine
    container_name: redis